# Generated by Django 2.0.6 on 2019-07-29 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tomato', 'Tomato'), ('eggplant', 'Eggplant'), ('celery', 'Celery'), ('egg', 'Egg'), ('milk', 'Milk'), ('fish', 'Fish'), ('chicken', 'Chicken'), ('oil', 'Oil')], max_length=1000)),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(max_length=1200, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='posts.Ingredients')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sendings',
                'verbose_name_plural': 'sendings',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
