# Generated by Django 2.0.6 on 2019-05-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'sendings', 'verbose_name_plural': 'sendings'},
        ),
    ]
