# Generated by Django 2.0.6 on 2019-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(related_name='posts', to='posts.Ingredients'),
        ),
    ]
