# Generated by Django 2.0.6 on 2019-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
